//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aik2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arts()
        {
            this.Pics = new HashSet<Pics>();
        }
    
        public int ArtId { get; set; }
        public string Mag { get; set; }
        public Nullable<int> IYear { get; set; }
        public string IMonth { get; set; }
        public string Author { get; set; }
        public string Name { get; set; }
        public Nullable<int> NN { get; set; }
        public string Serie { get; set; }
        public Nullable<int> NNN { get; set; }
        public string SerieSort { get; set; }
        public bool SortByName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pics> Pics { get; set; }
    }
}
