//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aik2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CraftsOld
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<int> IYear { get; set; }
        public Nullable<bool> YearBad { get; set; }
        public string Country { get; set; }
        public string Construct { get; set; }
        public int Source { get; set; }
        public Nullable<int> TxtBeg { get; set; }
        public Nullable<int> TxtEnd { get; set; }
        public Nullable<bool> Vert { get; set; }
        public Nullable<bool> Craft { get; set; }
        public Nullable<bool> MM { get; set; }
        public Nullable<bool> UAV { get; set; }
        public Nullable<bool> Glider { get; set; }
        public Nullable<int> S1 { get; set; }
        public Nullable<int> S2 { get; set; }
        public Nullable<int> S3 { get; set; }
        public Nullable<int> S4 { get; set; }
        public Nullable<int> S5 { get; set; }
        public Nullable<int> S6 { get; set; }
        public Nullable<int> S7 { get; set; }
        public Nullable<int> PicCnt { get; set; }
        public Nullable<int> TxtLen { get; set; }
        public Nullable<int> ParamCnt { get; set; }
    }
}
