//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aik2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crafts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Crafts()
        {
            this.Crafts1 = new HashSet<Crafts>();
            this.Crafts11 = new HashSet<Crafts>();
            this.Crafts12 = new HashSet<Crafts>();
            this.Pics = new HashSet<Pics>();
            this.WordLinks = new HashSet<WordLinks>();
        }
    
        public int CraftId { get; set; }
        public string Construct { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public Nullable<int> IYear { get; set; }
        public Nullable<bool> Vert { get; set; }
        public Nullable<bool> Uav { get; set; }
        public Nullable<bool> Glider { get; set; }
        public string Source { get; set; }
        public string Type { get; set; }
        public string CText { get; set; }
        public Nullable<int> SeeAlso { get; set; }
        public string Wiki { get; set; }
        public string Airwar { get; set; }
        public Nullable<int> FlyingM { get; set; }
        public string Wings { get; set; }
        public string Engines { get; set; }
        public Nullable<bool> LL { get; set; }
        public Nullable<bool> Proj { get; set; }
        public Nullable<int> Same { get; set; }
        public Nullable<bool> Single { get; set; }
        public Nullable<int> s1 { get; set; }
        public Nullable<int> s2 { get; set; }
        public Nullable<int> s3 { get; set; }
        public Nullable<int> s4 { get; set; }
        public Nullable<int> s5 { get; set; }
        public Nullable<int> s6 { get; set; }
        public Nullable<int> s7 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Crafts> Crafts1 { get; set; }
        public virtual Crafts Crafts2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Crafts> Crafts11 { get; set; }
        public virtual Crafts Crafts3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Crafts> Crafts12 { get; set; }
        public virtual Crafts Crafts4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pics> Pics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WordLinks> WordLinks { get; set; }
    }
}
