//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aik2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Links
    {
        public int LinkId { get; set; }
        public int Pict1 { get; set; }
        public int Pict2 { get; set; }
        public string Type1 { get; set; }
        public string Type2 { get; set; }
    
        public virtual Pics Pics { get; set; }
        public virtual Pics Pics1 { get; set; }
    }
}
