//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aik2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Links
    {
        public int LinkId { get; set; }
        public int Pict1 { get; set; }
        public int Pict2 { get; set; }
        public string Type1 { get; set; }
        public string Type2 { get; set; }
    
        public virtual Pics Pics { get; set; }
        public virtual Pics Pics1 { get; set; }
    }
}
