//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aik2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportId { get; set; }
        public string Mag { get; set; }
        public Nullable<int> IYear { get; set; }
        public string IMonth { get; set; }
        public string Source { get; set; }
        public Nullable<int> pics { get; set; }
        public Nullable<int> crafts { get; set; }
        public Nullable<int> uniq { get; set; }
    }
}
