//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aik2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serials
    {
        public string Serial { get; set; }
        public int PicId { get; set; }
        public int SerialID { get; set; }
        public bool IsSecondary { get; set; }
    
        public virtual Pics Pics { get; set; }
    }
}
