//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aik2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serials
    {
        public string Serial { get; set; }
        public int PicId { get; set; }
        public int SerialID { get; set; }
        public bool IsSecondary { get; set; }
    
        public virtual Pics Pics { get; set; }
    }
}
