//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aik2
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwArts
    {
        public int ArtId { get; set; }
        public string Mag { get; set; }
        public Nullable<int> IYear { get; set; }
        public string IMonth { get; set; }
        public string Author { get; set; }
        public string Name { get; set; }
        public Nullable<int> NN { get; set; }
        public string Serie { get; set; }
        public string Source { get; set; }
        public Nullable<int> cnt { get; set; }
        public string pic { get; set; }
    }
}
