//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aik2
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwArts
    {
        public int ArtId { get; set; }
        public string Mag { get; set; }
        public Nullable<int> IYear { get; set; }
        public string IMonth { get; set; }
        public string Author { get; set; }
        public string Name { get; set; }
        public Nullable<int> NN { get; set; }
        public string Serie { get; set; }
        public string Source { get; set; }
        public Nullable<int> cnt { get; set; }
        public string pic { get; set; }
        public Nullable<int> NNN { get; set; }
        public string SerieSort { get; set; }
        public bool SortByName { get; set; }
    }
}
