//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aik2
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCrafts
    {
        public int CraftId { get; set; }
        public string Construct { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public Nullable<int> IYear { get; set; }
        public Nullable<bool> Vert { get; set; }
        public Nullable<bool> Uav { get; set; }
        public Nullable<bool> Glider { get; set; }
        public string Source { get; set; }
        public string Type { get; set; }
        public Nullable<int> SeeAlso { get; set; }
        public string Wiki { get; set; }
        public string Airwar { get; set; }
        public Nullable<int> FlyingM { get; set; }
        public string Wings { get; set; }
        public string Engines { get; set; }
        public Nullable<bool> LL { get; set; }
        public Nullable<bool> Proj { get; set; }
        public Nullable<int> Same { get; set; }
        public Nullable<bool> Single { get; set; }
    }
}
