//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aik2
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCrafts
    {
        public int CraftId { get; set; }
        public string Construct { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public Nullable<int> IYear { get; set; }
        public Nullable<bool> Vert { get; set; }
        public Nullable<bool> Uav { get; set; }
        public Nullable<bool> Glider { get; set; }
        public string Source { get; set; }
        public string Type { get; set; }
        public Nullable<int> SeeAlso { get; set; }
        public string Wiki { get; set; }
        public string Airwar { get; set; }
        public Nullable<int> FlyingM { get; set; }
        public string Wings { get; set; }
        public string Engines { get; set; }
        public Nullable<bool> LL { get; set; }
        public Nullable<bool> Proj { get; set; }
        public Nullable<int> Same { get; set; }
        public Nullable<bool> Single { get; set; }
        public Nullable<int> PicCnt { get; set; }
        public Nullable<int> s1 { get; set; }
        public Nullable<int> s2 { get; set; }
        public Nullable<int> s3 { get; set; }
        public Nullable<int> s4 { get; set; }
        public Nullable<int> s5 { get; set; }
        public Nullable<int> s6 { get; set; }
        public Nullable<int> s7 { get; set; }
    }
}
