//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aik2
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPics
    {
        public int PicId { get; set; }
        public int ArtId { get; set; }
        public int CraftId { get; set; }
        public string XPage { get; set; }
        public string NN { get; set; }
        public Nullable<int> NNN { get; set; }
        public string Type { get; set; }
        public Nullable<int> NType { get; set; }
        public string Path { get; set; }
        public string Grp { get; set; }
        public string SText { get; set; }
        public string XType { get; set; }
    }
}
