//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aik2
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSerials
    {
        public int SerialID { get; set; }
        public string Serial { get; set; }
        public string SerialCraft { get; set; }
        public Nullable<int> cnt { get; set; }
        public int CraftId { get; set; }
    }
}
