//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aik2
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSerials
    {
        public int SerialID { get; set; }
        public string Serial { get; set; }
        public string SerialCraft { get; set; }
        public Nullable<int> cnt { get; set; }
        public int CraftId { get; set; }
    }
}
