//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aik2
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordLinks
    {
        public int WordLinkId { get; set; }
        public int WordId { get; set; }
        public Nullable<int> PicId { get; set; }
        public Nullable<int> CraftId { get; set; }
    
        public virtual Pics Pics { get; set; }
        public virtual Words Words { get; set; }
        public virtual Crafts Crafts { get; set; }
    }
}
