//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aik2
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordLinks
    {
        public int WordLinkId { get; set; }
        public int WordId { get; set; }
        public Nullable<int> PicId { get; set; }
        public Nullable<int> CraftId { get; set; }
    
        public virtual Pics Pics { get; set; }
        public virtual Words Words { get; set; }
        public virtual Crafts Crafts { get; set; }
    }
}
